name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: playwright-build
  cancel-in-progress: false
    
jobs:
  playwright-build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Static Code Analysis - Linting
      run: npm run lint
    - name: Static Code Analysis - Typechecking
      run: npm run typecheck
    - name: Static Code Analysis - Playwright Dry-run
      run: npm run test:dryrun
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 2

  publish-report:
    needs: [playwright-build]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Download a playwright html report
        uses: actions/download-artifact@v3
        with:
          name: playwright-report
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'playwright-report'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4